############################################################################
# apps/examples/sim_posix/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_EXAMPLES_SIM_POSIX_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_SIM_POSIX_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_SIM_POSIX_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_SIM_POSIX)

MAINSRC = sim_posix_main.c

include $(APPDIR)/Application.mk
