############################################################################
# apps/examples/hostfs_longpath/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_EXAMPLES_HOSTFS_LONGPATH_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_HOSTFS_LONGPATH_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_HOSTFS_LONGPATH_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_HOSTFS_LONGPATH)

MAINSRC = hostfs_longpath_main.c

include $(APPDIR)/Application.mk
