############################################################################
# apps/examples/loadelf/sim/src/Makefile
#
# SPDX-License-Identifier: Apache-2.0
#
# Reuse the upstream NuttX sim board sources.
############################################################################

SIM_BOARD_SRCDIR := $(TOPDIR)/boards/sim/sim/sim/src

VPATH += $(SIM_BOARD_SRCDIR)
DEPPATH += --dep-path $(SIM_BOARD_SRCDIR)

include $(SIM_BOARD_SRCDIR)/Makefile
